/**
 * This file is autogenerated by Scaffold-ETH.
 * You should not edit it manually or your changes might be overwritten.
 */
import { GenericContractsDeclaration } from "~~/utils/scaffold-eth/contract";

const deployedContracts = {
  31337: {
    DeliveryStore: {
      address: "0xa513E6E4b8f2a923D98304ec87F64353C4D5C853",
      abi: [
        {
          inputs: [
            {
              internalType: "address",
              name: "_owner",
              type: "address",
            },
          ],
          stateMutability: "nonpayable",
          type: "constructor",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: false,
              internalType: "uint256",
              name: "channelId",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "address",
              name: "customer",
              type: "address",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "channelBalance",
              type: "uint256",
            },
          ],
          name: "ChannelClosed",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: false,
              internalType: "uint256",
              name: "channelId",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "address",
              name: "customer",
              type: "address",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "deposit",
              type: "uint256",
            },
          ],
          name: "ChannelOpened",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: false,
              internalType: "uint256",
              name: "orderId",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "address",
              name: "customer",
              type: "address",
            },
            {
              indexed: false,
              internalType: "string",
              name: "product",
              type: "string",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "price",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "enum DeliveryStore.DeliveryStatus",
              name: "status",
              type: "uint8",
            },
            {
              indexed: false,
              internalType: "address",
              name: "deliveryPersonAddress",
              type: "address",
            },
          ],
          name: "OrderPlaced",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "address",
              name: "previousOwner",
              type: "address",
            },
            {
              indexed: true,
              internalType: "address",
              name: "newOwner",
              type: "address",
            },
          ],
          name: "OwnershipTransferred",
          type: "event",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          name: "channels",
          outputs: [
            {
              internalType: "address",
              name: "customer",
              type: "address",
            },
            {
              internalType: "uint256",
              name: "channelBalance",
              type: "uint256",
            },
            {
              internalType: "bool",
              name: "isOpen",
              type: "bool",
            },
            {
              internalType: "bytes32",
              name: "orderIdentifier",
              type: "bytes32",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "confirmDelivery",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [],
          name: "openChannel",
          outputs: [],
          stateMutability: "payable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "string",
              name: "_product",
              type: "string",
            },
          ],
          name: "orderProduct",
          outputs: [],
          stateMutability: "payable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          name: "orders",
          outputs: [
            {
              internalType: "uint256",
              name: "orderId",
              type: "uint256",
            },
            {
              internalType: "address",
              name: "customer",
              type: "address",
            },
            {
              internalType: "string",
              name: "product",
              type: "string",
            },
            {
              internalType: "uint256",
              name: "price",
              type: "uint256",
            },
            {
              internalType: "enum DeliveryStore.DeliveryStatus",
              name: "status",
              type: "uint8",
            },
            {
              internalType: "address",
              name: "deliveryPersonAddress",
              type: "address",
            },
            {
              internalType: "uint256",
              name: "channelId",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "owner",
          outputs: [
            {
              internalType: "address",
              name: "",
              type: "address",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "renounceOwnership",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "_orderId",
              type: "uint256",
            },
            {
              internalType: "address",
              name: "_deliveryPersonAddress",
              type: "address",
            },
          ],
          name: "setDeliveryPerson",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "newOwner",
              type: "address",
            },
          ],
          name: "transferOwnership",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          stateMutability: "payable",
          type: "receive",
        },
      ],
      inheritedFunctions: {
        owner: "@openzeppelin/contracts/access/Ownable.sol",
        renounceOwnership: "@openzeppelin/contracts/access/Ownable.sol",
        transferOwnership: "@openzeppelin/contracts/access/Ownable.sol",
      },
    },
  },
} as const;

export default deployedContracts satisfies GenericContractsDeclaration;
